//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceDepartamento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Departamento", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Departamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDepartamento.ServicioDepartamentoSoap")]
    public interface ServicioDepartamentoSoap {
        
        // CODEGEN: Generating message contract since element name departamento from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarDepartamento", ReplyAction="*")]
        CapaGUI.ServiceDepartamento.insertarDepartamentoResponse insertarDepartamento(CapaGUI.ServiceDepartamento.insertarDepartamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarDepartamento", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceDepartamento.insertarDepartamentoResponse> insertarDepartamentoAsync(CapaGUI.ServiceDepartamento.insertarDepartamentoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarDepartamentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarDepartamento", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceDepartamento.insertarDepartamentoRequestBody Body;
        
        public insertarDepartamentoRequest() {
        }
        
        public insertarDepartamentoRequest(CapaGUI.ServiceDepartamento.insertarDepartamentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarDepartamentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceDepartamento.Departamento departamento;
        
        public insertarDepartamentoRequestBody() {
        }
        
        public insertarDepartamentoRequestBody(CapaGUI.ServiceDepartamento.Departamento departamento) {
            this.departamento = departamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarDepartamentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarDepartamentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceDepartamento.insertarDepartamentoResponseBody Body;
        
        public insertarDepartamentoResponse() {
        }
        
        public insertarDepartamentoResponse(CapaGUI.ServiceDepartamento.insertarDepartamentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarDepartamentoResponseBody {
        
        public insertarDepartamentoResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioDepartamentoSoapChannel : CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDepartamentoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap>, CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap {
        
        public ServicioDepartamentoSoapClient() {
        }
        
        public ServicioDepartamentoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDepartamentoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDepartamentoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDepartamentoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceDepartamento.insertarDepartamentoResponse CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap.insertarDepartamento(CapaGUI.ServiceDepartamento.insertarDepartamentoRequest request) {
            return base.Channel.insertarDepartamento(request);
        }
        
        public void insertarDepartamento(CapaGUI.ServiceDepartamento.Departamento departamento) {
            CapaGUI.ServiceDepartamento.insertarDepartamentoRequest inValue = new CapaGUI.ServiceDepartamento.insertarDepartamentoRequest();
            inValue.Body = new CapaGUI.ServiceDepartamento.insertarDepartamentoRequestBody();
            inValue.Body.departamento = departamento;
            CapaGUI.ServiceDepartamento.insertarDepartamentoResponse retVal = ((CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap)(this)).insertarDepartamento(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceDepartamento.insertarDepartamentoResponse> CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap.insertarDepartamentoAsync(CapaGUI.ServiceDepartamento.insertarDepartamentoRequest request) {
            return base.Channel.insertarDepartamentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceDepartamento.insertarDepartamentoResponse> insertarDepartamentoAsync(CapaGUI.ServiceDepartamento.Departamento departamento) {
            CapaGUI.ServiceDepartamento.insertarDepartamentoRequest inValue = new CapaGUI.ServiceDepartamento.insertarDepartamentoRequest();
            inValue.Body = new CapaGUI.ServiceDepartamento.insertarDepartamentoRequestBody();
            inValue.Body.departamento = departamento;
            return ((CapaGUI.ServiceDepartamento.ServicioDepartamentoSoap)(this)).insertarDepartamentoAsync(inValue);
        }
    }
}
